@startuml Squash Game
start
:モジュールのインポート;
:ウインドウの作成;
:ゲームのメイン処理;
:ゲームの初期化（変数の設定）\n★「ゲームスタート」のメッセージを表示;

repeat :画面の描画;
:画面クリア\nキャンバス（画面）の作成\nボールを描く\nラケットを書く\nボールの移動;
fork
    if (左右の壁に当たったか？) then (イエス)
        :ボール反転;
    else (ノー)
    endif
fork again
    if (上下の壁に当たったか？) then (イエス)
        :ボール反転;
    else (ノー)
    endif
fork again
    if (ラケットに当たったか？) then (イエス)
        :ボール反転\n★乱数によって右か左に\n方向を変える;
    else (ノー)
    endif
end fork
:マウスの動きの確認\n★マウスのポインター位置を調べる;
:マウスボタンの確認\n★マウスの左ボタンが押されたかどうかを調べる;
:ゲームの繰り返し;
:ウィンドウの描画;

@enduml
