@startuml okonomiyaki
start
:材料(小麦粉、水、キャベツ、ブタ肉、イカ、\nソース、カツオ節、青ノリ、食用油食用油)をそろえる;
:小麦粉を水で溶く;

fork
    :キャベツと肉とイカをきざむ;
fork again
    :きざんだキャベツと肉とイカを\n水で溶いた小麦粉の中に入れてかき混ぜる;
end  fork
:ホットプレートのスイッチを入れる;

while (ホットプレートが熱くなったか？) is (ノー)
    :待つ;
endwhile (イエス)

:溶いた小麦粉をおたまで流しこむ;
:おたまの背で形を丸く整える;

while (片面が焼けたか？) is (ノー)
    :待つ;
endwhile (イエス)
:ひっくり返す;
while (もう片面も焼けたか？) is (ノー)
    :待つ;
endwhile (イエス)

:ソースを塗って\nカツオ節と青ノリをかける;
:お皿に取る;
:食べる;
end
@enduml
